site_name: OpenOasis


docs_dir: 'Doc'
nav:
  - Home: 
    - 'intro': README.md 
    - 'Models': 
      - 'Oasis API': models\namespace_open_oasis.md
      - 'Solvers': models\namespace_open_oasis_1_1_comm_imp_1_1_numeric.md
      - 'Heats': models\namespace_open_oasis_1_1_syst_heats.md 
    - 'iAgents': 
      - 'Spark': iAgents\README.md      
    - 'Data Assistants':
      - 'Converters': DataAssts\README.md           
  - Devs: OpenOasisDevTips.md


theme:
  # name: rtd-dropdown
  name: readthedocs
  language: zh  
  palette:  
    primary: light blue
    accent: indigo
  feature:
    tabs: true  


markdown_extensions:
  - admonition 
  - footnotes 
  - meta 
  - pymdownx.caret  
  - pymdownx.tilde  
  - pymdownx.critic  
  - pymdownx.details 
  - pymdownx.inlinehilite 
  - pymdownx.mark 
  - pymdownx.smartsymbols  
  - pymdownx.superfences  
  - codehilite:   
      guess_lang: false
      linenums: true
  - toc:  
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:  
      smart_enable: all
  - pymdownx.emoji:  
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  
  - pymdownx.tasklist: 
      custom_checkbox: true


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false  
            inherited_members: true
            merge_init_into_class: true
            heading_level: 3  
  - mkdoxy:
      projects:
        models: 
          src-dirs: Models/Inc Models/SystHeats Models/CommImp/IO Models/CommImp/Numeric Models/CommImp/Temporal Models/CommImp/Spatial
          full-doc: True
          doxy-cfg: 
            FILE_PATTERNS: "*.cpp *.h*"
            RECURSIVE: True 


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js