# This is a basic workflow to help you get started with Actions

name: OpenOasis_Linux_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Linux OpenOasis Actions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GCC-10
        run: |
          sudo apt-get update
          sudo apt install gcc-10 g++-10 -y
          gcc --version
          g++ --version
          ls /usr/bin/gcc*
        shell: bash
      - name: Install Third party library
        run: |
          git clone -b v2.11.0 --depth=1 https://github.com/pybind/pybind11.git
          cd  pybind11
          mkdir build
          cd build
          cmake ..
          sudo make install
          export PATH=/usr/local/share/cmake/:$PATH
        shell: bash
      - name: CMake Build and Install
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir build
          cd build
          cmake .. -DENABLE_TESTS=on -DENABLE_PYLIB=on
          cmake --build . --config Release
          ctest -C Release -VV
          cmake --install .
        shell: bash 
