# This is a basic workflow to help you get started with Actions

name: Macos_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Macos OpenOasis Actions"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler
        run: |    
          brew install llvm    
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++
          export LDFLAGS="-L/usr/local/opt/llvm/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
        shell: bash
      - name: Install Third party library
        run: |
          git clone https://github.com/pybind/pybind11.git
          cd  pybind11
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          sudo cmake --install .
        shell: bash
      - name: CMake Build
        run: |
          export pybind11_DIR=/usr/local/share/cmake/pybind11/
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DENABLE_TESTS=on -DENABLE_PYLIB=on
          cmake --build . --config Release
        shell: bash 
      - name: Ctest
        run: |
          cd ${{ github.workspace }}/build
          ctest --output-on-failure -C Release -VV
        shell: bash 