# This is a basic workflow to help you get started with Actions

name: Windows_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Windows OpenOasis Actions"
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Third party library
        run: |
          cd D:/a
          git clone https://github.com/pybind/pybind11.git
          cd pybind11
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=install
          cmake --build . --config Release
          cmake --install .
      - name: CMake Build
        run: |   
          cd "D:/a/pybind11/build/install/share/cmake/"
          ls
          echo "pybind11_DIR=hhh" | Out-File -FilePath $env:GITHUB_ENV -Append  
          echo "${{ env.pybind11_DIR }}" 
          cd D:/a/OpenOasis/OpenOasis
          ls
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"        