# This is a basic workflow to help you get started with Actions

name: Windows_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Windows OpenOasis Actions"
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Third party library
        run: |
          git clone https://github.com/pybind/pybind11.git
          cd pybind11
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=install
          cmake --build . --config Release
          cmake --install .
        shell: bash
      - name: CMake Build
        run: |
          $Env:pybind11_DIR = D:/a/OpenOasis/OpenOasis/pybind11/build/install/share/cmake/         
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DENABLE_TESTS=on -DENABLE_PYLIB=on
          cmake --build . --config Release
        shell: bash 
      - name: Ctest
        run: |
          cd ${{ github.workspace }}/build
          ctest --output-on-failure -C Release -VV
        shell: bash 
      - name: CMake Install
        run: |
          cd ${{ github.workspace }}/build
          cmake --install .
        shell: bash 
        